import type { VisibleSettings } from './types';

export const VISIBLE_SETTINGS_DEFAULTS: Readonly<VisibleSettings> = Object.freeze({
  lockStamina: true,
  revealAllOnStepTile: false,
  expMultiplier: 1,
  battleSkillExpMultiplier: 1,
  creationPointMultiplier: 1,
  horseBaseSpeedMultiplier: 1,
  horseTurboSpeedMultiplier: 1,
  horseTurboDurationMultiplier: 1,
  horseTurboCooldownMultiplier: 1,
  lockHorseTurboStamina: true,
  horseStaminaMultiplier: 1,
  carryWeightCap: 100000,
  ignoreCarryWeight: false,
  merchantCarryCash: 100000,
  treasureTradeHelperEnabled: true,
  treasureAutoTradeEnabled: true,
  materialAutoBuyEnabled: true,
  materialPurchaseMinRareLv: 0,
  materialPurchaseMinItemLv: 0,
  shopOwnershipEnabled: true,
  skillBookOwnershipIndicatorEnabled: true,
  mogaoDiscipleForgettingEnabled: true,
  auctionEventAlwaysRedEnabled: true,
  auctionPreviewRefreshEnabled: true,
  auctionPreviewRefreshHotkey: 'R',
  governmentStorageRefreshEnabled: true,
  governmentStorageRefreshHotkey: 'R',
  yellowCraneCandidateRefreshEnabled: true,
  yellowCraneCandidateRefreshHotkey: 'R',
  forceBountyRefreshEnabled: true,
  commonBountyRefreshEnabled: true,
  governBountyRefreshEnabled: true,
  bountyRefreshHotkey: 'R',
  treasureIdentifyBestValueAssistEnabled: true,
  breakthroughRerollEnabled: true,
  craftRerollEnabled: true,
  luckyHitChancePercent: 0,
  relationshipFeaturesEnabled: false,
  extraRelationshipGainChancePercent: 0,
  teamAutoFavorEnabled: true,
  teamAutoFavorPerDay: 5,
  teamFameShareEnabled: true,
  teamFameSharePercent: 30,
  blockOverflowLoverHomeBattle: true,
  sameSectAreaShareEnabled: true,
  characterDataTestHotkeyEnabled: false,
  maxLoverCount: 8,
  debatePlayerDamageTakenMultiplier: 1,
  debateEnemyDamageTakenMultiplier: 1,
  craftRandomPickUpgrade: true,
  craftTier1ExtraItems: 0,
  craftTier2ExtraItems: 1,
  craftTier3ExtraItems: 2,
  craftTier4ExtraItems: 3,
  craftTier5ExtraItems: 4,
  drinkPlayerPowerCostMultiplier: 1,
  drinkEnemyPowerCostMultiplier: 1,
  dialogMonthlyLimitMultiplier: 3,
  dialogFastForwardAssistEnabled: false,
  dailySkillInsightChancePercent: 0,
  dailySkillInsightExpPercent: 5,
  dailySkillInsightUseRarityScaling: true,
  dailySkillInsightRealtimeIntervalSeconds: 0,
  skillTalentEnabled: true,
  skillTalentLevelThreshold: 10,
  skillTalentTierPointMultiplier: 2,
  skillTalentPlayerOnly: true,
  freezeDate: false,
  freezeHotkey: 'F1',
  outsideBattleSpeedHotkey: 'F11',
  battleTurboEnabled: true,
  battleTurboHotkey: 'F8'
});

function clamp(value: number, min: number, max: number): number {
  if (Number.isNaN(value)) {
    return min;
  }

  return Math.min(max, Math.max(min, value));
}

function normalizeHotkey(value: string | undefined, fallback: string): string {
  const trimmed = value?.trim();
  return trimmed && trimmed.length > 0 ? trimmed : fallback;
}

export function createDefaultVisibleSettings(): VisibleSettings {
  return { ...VISIBLE_SETTINGS_DEFAULTS };
}

export function sanitizeVisibleSettings(input: VisibleSettings): VisibleSettings {
  const defaults = VISIBLE_SETTINGS_DEFAULTS;
  return {
    lockStamina: input.lockStamina,
    revealAllOnStepTile: input.revealAllOnStepTile,
    expMultiplier: Math.round(clamp(input.expMultiplier, 1, 999)),
    battleSkillExpMultiplier: Math.round(clamp(input.battleSkillExpMultiplier, 1, 999)),
    creationPointMultiplier: Math.round(clamp(input.creationPointMultiplier, 1, 999)),
    horseBaseSpeedMultiplier: clamp(input.horseBaseSpeedMultiplier, 0.01, 999),
    horseTurboSpeedMultiplier: clamp(input.horseTurboSpeedMultiplier, 0.01, 999),
    horseTurboDurationMultiplier: clamp(input.horseTurboDurationMultiplier, 0.01, 999),
    horseTurboCooldownMultiplier: clamp(input.horseTurboCooldownMultiplier, 0.01, 999),
    lockHorseTurboStamina: input.lockHorseTurboStamina,
    horseStaminaMultiplier: clamp(input.horseStaminaMultiplier, 0.01, 999),
    carryWeightCap: clamp(input.carryWeightCap, 0, 999999999),
    ignoreCarryWeight: input.ignoreCarryWeight,
    merchantCarryCash: Math.round(clamp(input.merchantCarryCash, 0, 999999999)),
    treasureTradeHelperEnabled: input.treasureTradeHelperEnabled,
    treasureAutoTradeEnabled: input.treasureAutoTradeEnabled,
    materialAutoBuyEnabled: input.materialAutoBuyEnabled,
    materialPurchaseMinRareLv: Math.round(clamp(input.materialPurchaseMinRareLv, 0, 5)),
    materialPurchaseMinItemLv: Math.round(clamp(input.materialPurchaseMinItemLv, 0, 5)),
    shopOwnershipEnabled: input.shopOwnershipEnabled,
    skillBookOwnershipIndicatorEnabled: input.skillBookOwnershipIndicatorEnabled,
    mogaoDiscipleForgettingEnabled: input.mogaoDiscipleForgettingEnabled,
    auctionEventAlwaysRedEnabled: input.auctionEventAlwaysRedEnabled,
    auctionPreviewRefreshEnabled: input.auctionPreviewRefreshEnabled,
    auctionPreviewRefreshHotkey: normalizeHotkey(input.auctionPreviewRefreshHotkey, defaults.auctionPreviewRefreshHotkey),
    governmentStorageRefreshEnabled: input.governmentStorageRefreshEnabled,
    governmentStorageRefreshHotkey: normalizeHotkey(
      input.governmentStorageRefreshHotkey,
      defaults.governmentStorageRefreshHotkey
    ),
    yellowCraneCandidateRefreshEnabled: input.yellowCraneCandidateRefreshEnabled,
    yellowCraneCandidateRefreshHotkey: normalizeHotkey(
      input.yellowCraneCandidateRefreshHotkey,
      defaults.yellowCraneCandidateRefreshHotkey
    ),
    forceBountyRefreshEnabled: input.forceBountyRefreshEnabled,
    commonBountyRefreshEnabled: input.commonBountyRefreshEnabled,
    governBountyRefreshEnabled: input.governBountyRefreshEnabled,
    bountyRefreshHotkey: normalizeHotkey(input.bountyRefreshHotkey, defaults.bountyRefreshHotkey),
    treasureIdentifyBestValueAssistEnabled: input.treasureIdentifyBestValueAssistEnabled,
    breakthroughRerollEnabled: input.breakthroughRerollEnabled,
    craftRerollEnabled: input.craftRerollEnabled,
    luckyHitChancePercent: Math.round(clamp(input.luckyHitChancePercent, 0, 100)),
    relationshipFeaturesEnabled: input.relationshipFeaturesEnabled,
    extraRelationshipGainChancePercent: Math.round(clamp(input.extraRelationshipGainChancePercent, 0, 100)),
    teamAutoFavorEnabled: input.teamAutoFavorEnabled,
    teamAutoFavorPerDay: clamp(input.teamAutoFavorPerDay, 0, 999),
    teamFameShareEnabled: input.teamFameShareEnabled,
    teamFameSharePercent: clamp(input.teamFameSharePercent, 0, 100),
    blockOverflowLoverHomeBattle: input.blockOverflowLoverHomeBattle,
    sameSectAreaShareEnabled: input.sameSectAreaShareEnabled,
    characterDataTestHotkeyEnabled: input.characterDataTestHotkeyEnabled,
    maxLoverCount: Math.round(clamp(input.maxLoverCount, 1, 999)),
    debatePlayerDamageTakenMultiplier: clamp(input.debatePlayerDamageTakenMultiplier, 0, 999),
    debateEnemyDamageTakenMultiplier: clamp(input.debateEnemyDamageTakenMultiplier, 0, 999),
    craftRandomPickUpgrade: input.craftRandomPickUpgrade,
    craftTier1ExtraItems: Math.round(clamp(input.craftTier1ExtraItems, 0, 999)),
    craftTier2ExtraItems: Math.round(clamp(input.craftTier2ExtraItems, 0, 999)),
    craftTier3ExtraItems: Math.round(clamp(input.craftTier3ExtraItems, 0, 999)),
    craftTier4ExtraItems: Math.round(clamp(input.craftTier4ExtraItems, 0, 999)),
    craftTier5ExtraItems: Math.round(clamp(input.craftTier5ExtraItems, 0, 999)),
    drinkPlayerPowerCostMultiplier: clamp(input.drinkPlayerPowerCostMultiplier, 0, 999),
    drinkEnemyPowerCostMultiplier: clamp(input.drinkEnemyPowerCostMultiplier, 0, 999),
    dialogMonthlyLimitMultiplier: clamp(input.dialogMonthlyLimitMultiplier, 0, 999),
    dialogFastForwardAssistEnabled: input.dialogFastForwardAssistEnabled,
    dailySkillInsightChancePercent: Math.round(clamp(input.dailySkillInsightChancePercent, 0, 100)),
    dailySkillInsightExpPercent: clamp(input.dailySkillInsightExpPercent, 0, 999),
    dailySkillInsightUseRarityScaling: input.dailySkillInsightUseRarityScaling,
    dailySkillInsightRealtimeIntervalSeconds: clamp(input.dailySkillInsightRealtimeIntervalSeconds, 0, 999),
    skillTalentEnabled: input.skillTalentEnabled,
    skillTalentLevelThreshold: Math.round(clamp(input.skillTalentLevelThreshold, 1, 999)),
    skillTalentTierPointMultiplier: clamp(input.skillTalentTierPointMultiplier, 0.1, 999),
    skillTalentPlayerOnly: input.skillTalentPlayerOnly,
    freezeDate: input.freezeDate,
    freezeHotkey: normalizeHotkey(input.freezeHotkey, defaults.freezeHotkey),
    outsideBattleSpeedHotkey: normalizeHotkey(input.outsideBattleSpeedHotkey, defaults.outsideBattleSpeedHotkey),
    battleTurboEnabled: input.battleTurboEnabled,
    battleTurboHotkey: normalizeHotkey(input.battleTurboHotkey, defaults.battleTurboHotkey)
  };
}
